// =============================================
// UMKM Ngadirejo - TypeScript Type Definitions
// Frontend-facing types for the application
//
// Database row types are auto-generated by Prisma
// and should NOT be duplicated here.
// =============================================

// --- Operational Schedule Types ---

export type HariType = 'senin' | 'selasa' | 'rabu' | 'kamis' | 'jumat' | 'sabtu' | 'minggu';

export interface JamHarian {
  buka: string;
  tutup: string;
  libur: boolean;
}

export interface JamOperasional {
  senin: JamHarian;
  selasa: JamHarian;
  rabu: JamHarian;
  kamis: JamHarian;
  jumat: JamHarian;
  sabtu: JamHarian;
  minggu: JamHarian;
}

// --- Aggregated Frontend Types ---

/**
 * Full UMKM detail — used on detail page (/umkm/[slug])
 * Result of JOIN queries across all related tables
 */
export interface Umkm {
  id: number;
  slug: string;
  nama: string;
  pemilik: string;
  kategori: string;
  deskripsiSingkat: string;
  deskripsiLengkap: string;
  produk: string[];
  tags: string[];
  whatsapp: string;
  alamat: string;
  jamOperasional: JamOperasional;
  latitude: number;
  longitude: number;
  googleMapsUrl: string;
  fotoUtama: string;
  galeri: string[];
}

/**
 * Lightweight UMKM item — used on listing/card views
 * Only includes fields needed for rendering cards
 */
export interface UmkmListItem {
  id: number;
  slug: string;
  nama: string;
  pemilik: string;
  kategori: string;
  deskripsiSingkat: string;
  tags: string[];
  whatsapp: string;
  alamat: string;
  latitude: number;
  longitude: number;
  fotoUtama: string;
  jamOperasional: JamOperasional;
}

/** UMKM item with calculated distance (client-side) */
export interface UmkmWithDistance extends UmkmListItem {
  distance?: number;
}

/** Aggregate stats for the hero section */
export interface UmkmStats {
  totalUmkm: number;
  totalKategori: number;
}
